version: '3.8'

services:
  recipe-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: recipe-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - recipe-network

networks:
  recipe-network:
    driver: bridge
